### PR TITLE
Avoid conflict in the global namespace by importing `sourcekittendaemon.py`.

### PR DESCRIPTION
**Pull request by mitsuse**
## Modifications
- Import `sourcekittendaemon.py and execute`sourcekittendaemon.main`instead of calling`main`.
## Reason

This is an alternative suggestion for #1.

When Vim executes scripts with `:python` or `:pyfile`, these consume the global namespace.
Possibly they conflict names defined in other files called by another plugins.
So, I avoided conflict by accessing `main` via `sourcekiitendaemon` module. This name of module seems not to be used by other plugins.

### CODE REVIEW

**Comment by keith** [comment]
Can you fix the conflicts created by merging #1 here?

**Comment by mitsuse** [comment]
@keith Thanks for mergin #1!! This pull-request is an alternative for #1, so you don't need to merge this.

**Comment by keith** [comment]
Awesome. Can we close this one then?

**Comment by keith** [comment]
Thanks!

**Pull request closed without merging**
